addons:
  apt:
    packages:
      - python-pygments

install:
  - pwd
  - ls
  - rm -rf public || exit 0

script:
  - pwd
  - ls
  - bin/hugo --theme=hugo-future-imperfect

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source